# make use of vm's 
sudo: 'required'
services:
  - docker
install:
  - docker build -t sachinkgaikwad/nginx  .
  - docker run -d -p 127.0.0.1:80:80 --name nginx sachinkgaikwad/nginx

script:
  - docker ps | grep -i nginx
