version: 0.2

phases:
  build:
    commands:
      - docker build -t sachinkgaikwad/webapp .
#      - docker tag sachinkgaikwad/webapp:latest 459297701547.dkr.ecr.us-east-2.amazonaws.com/parallax-ecr:latest
  post_build:
    commands: 
#      - eval `aws ecr get-login   --region us-east-2      --no-include-email`
#      - docker push 459297701547.dkr.ecr.us-east-2.amazonaws.com/parallax-ecr:latestsachinkgaikwad/webapp
       - docker push sachinkgaikwad/webapp:latest
